module.exports = {
    authController : require('./auth_controller'),
    branchController: require('./branch_controller'),
    branchTypeController: require('./branchType_controller'),
    changePasswordController: require('./changePassword_controller'),
    companyController : require('./company_controller'),
    paymentController : require('./payment_controller'),
    paymentStateController : require('./paymentState_controller'),
    paymentDetailController : require('./paymentDetail_controller'),
    personTypeController: require('./personType_controller'),
    personController: require('./person_controller'),
    reservationController: require('./reservation_controller'),
    reservationDetailController: require('./reservationDetail_controller'),
    reservationStateController: require('./reservationState_controller'),
    roleController : require('./role_controller'),
    roomController: require('./room_controller'),
    roomPriceController: require('./roomPrice_controller'),
    roomPriceRoomController: require('./roomPrice_room_controller'),
    roomServiceController: require('./room_service_controller'),
    roomStateController: require('./roomState_controller'),
    serviceController: require('./service_controller'),
    userController : require('./user_controller'),
}